import os
import re
import shutil
import sys
from pathlib import Path

from textnode import TextNode, TextType, BlockType
from htmlnode import ParentNode, LeafNode

def text_node_to_html_node(text_node):
    if text_node.text_type == TextType.TEXT:
        return LeafNode(None, text_node.text)
    elif text_node.text_type == TextType.BOLD:
        return LeafNode("b", text_node.text)
    elif text_node.text_type == TextType.ITALIC:
        return LeafNode("i", text_node.text)
    elif text_node.text_type == TextType.CODE:
        return LeafNode("code", text_node.text)
    elif text_node.text_type == TextType.LINK:
        return LeafNode("a", text_node.text, props={"href": text_node.url})
    elif text_node.text_type == TextType.IMAGE:
        return LeafNode("img", None, props={"src": text_node.url, "alt": text_node.text})
    else:
        raise Exception(f"invalid text type: {text_node.text_type}")

def split_nodes_delimiter(old_nodes: list[TextNode], delimiter: str, text_type: TextType) -> list[TextNode]:
    new_nodes = []
    for node in old_nodes:
        if node.text_type != TextType.TEXT:
            new_nodes.append(node)
            continue

        split_text = node.text.split(delimiter)
        if len(split_text) % 2 == 0:
            raise ValueError(f"invalid markdown syntax, unmatched delimiter: {delimiter}")

        for i, text in enumerate(split_text):
            if text == "":
                continue
            if i % 2 == 0:
                new_nodes.append(TextNode(text, TextType.TEXT))
            else:
                new_nodes.append(TextNode(text, text_type))

    return new_nodes

def split_nodes_image(old_nodes: list[TextNode]) -> list[TextNode]:
    return split_nodes_markdown(old_nodes, extract_markdown_images, TextType.IMAGE, "!")

def split_nodes_link(old_nodes: list[TextNode]) -> list[TextNode]:
    return split_nodes_markdown(old_nodes, extract_markdown_links, TextType.LINK)

def extract_markdown_images(text):
    return re.findall(r"!\[([^\[\]]*)\]\(([^\(\)]*)\)", text)

def extract_markdown_links(text):
    return re.findall(r"(?<!!)\[([^\[\]]*)\]\(([^\(\)]*)\)", text)

def split_nodes_markdown(old_nodes, extractor, text_type, prefix=""):
    new_nodes = []
    for node in old_nodes:
        if node.text_type != TextType.TEXT:
            new_nodes.append(node)
            continue

        remaining_text = node.text
        matches = extractor(remaining_text)
        for text, url in matches:
            markdown = f"{prefix}[{text}]({url})"
            sections = remaining_text.split(markdown, 1)
            if sections[0] != "":
                new_nodes.append(TextNode(sections[0], TextType.TEXT))
            new_nodes.append(TextNode(text, text_type, url))
            remaining_text = sections[1]

        if remaining_text != "":
            new_nodes.append(TextNode(remaining_text, TextType.TEXT))

    return new_nodes

def text_to_textnodes(text):
    textnodes = []
    textnodes.append(TextNode(text, TextType.TEXT))
    bold_nodes = split_nodes_delimiter(textnodes, "**", TextType.BOLD)
    italic_nodes = split_nodes_delimiter(bold_nodes, "_", TextType.ITALIC)
    code_nodes = split_nodes_delimiter(italic_nodes, "`", TextType.CODE)
    image_nodes = split_nodes_image(code_nodes)
    link_nodes = split_nodes_link(image_nodes)
    return link_nodes

def markdown_to_blocks(markdown):
    blocks = markdown.split('\n\n')
    # print(f"blocks before stripping: {blocks}")  # Debugging line
    # Code below generated by Codex to only keep non-empty blocks and strip whitespace
    blocks = [block.strip() for block in blocks if block.strip()]
    # print(f"blocks after stripping: {blocks}")  # Debugging line
    return blocks


def extract_title(markdown):
    for line in markdown.splitlines():
        match = re.match(r'^\s*#(?!#)\s*(.+?)\s*$', line)
        if match:
            return match.group(1).strip()
    raise Exception("No h1 header found in markdown")


def normalize_basepath(basepath):
    if basepath is None:
        return "/"
    basepath = basepath.strip()
    if not basepath or basepath == "/":
        return "/"
    if not basepath.startswith("/"):
        basepath = f"/{basepath}"
    return basepath.rstrip("/")


def generate_page(from_path, template_path, dest_path, basepath="/"):
    from_path = Path(from_path)
    template_path = Path(template_path)
    dest_path = Path(dest_path)
    basepath = normalize_basepath(basepath)

    print(f"Generating page from {from_path} to {dest_path} using {template_path}")

    markdown = from_path.read_text(encoding="utf-8")
    template = template_path.read_text(encoding="utf-8")

    html_node = markdown_to_html_node(markdown)
    content_html = html_node.to_html()
    title = extract_title(markdown)

    output_html = template.replace("{{ Title }}", title).replace("{{ Content }}", content_html)
    if basepath != "/":
        output_html = output_html.replace('href="/', f'href="{basepath}/')
        output_html = output_html.replace('src="/', f'src="{basepath}/')

    dest_path.parent.mkdir(parents=True, exist_ok=True)
    dest_path.write_text(output_html, encoding="utf-8")

    return dest_path


def generate_pages_recursive(dir_path_content, template_path, dest_dir_path, basepath="/"):
    dir_path_content = Path(dir_path_content)
    template_path = Path(template_path)
    dest_dir_path = Path(dest_dir_path)

    for path in dir_path_content.rglob("*"):
        if path.is_dir():
            continue
        if path.suffix != ".md":
            continue

        relative_path = path.relative_to(dir_path_content)
        dest_path = dest_dir_path / relative_path.with_suffix(".html")
        generate_page(path, template_path, dest_path, basepath=basepath)


def block_to_block_type(block):
    match = re.match(r'^(#{1,6})\s+(.*)$', block)
    if match:
        return BlockType.HEADING
    elif block.startswith("```\n") and block.endswith("```"):
        return BlockType.CODE
    elif block.startswith(">"):
        return BlockType.QUOTE
    elif re.match(r"^\d+\.\s", block):
        return BlockType.ORDERED_LIST
    elif block.startswith("- "):
        return BlockType.UNORDERED_LIST
    else:
        return BlockType.PARAGRAPH


def text_to_children(text):
    return [text_node_to_html_node(node) for node in text_to_textnodes(text)]


def get_heading_level(block):
    match = re.match(r'^(#{1,6})\s+', block)
    return len(match.group(1)) if match else 1


def strip_heading_markers(block):
    return re.sub(r'^(#{1,6})\s+', '', block).strip()


def build_heading_node(block):
    heading_text = strip_heading_markers(block)
    heading_level = get_heading_level(block)
    return ParentNode(f"h{heading_level}", text_to_children(heading_text))


def build_paragraph_node(block):
    return ParentNode("p", text_to_children(block))


def build_quote_node(block):
    quote_text = re.sub(r'^>\s?', '', block).strip()
    return ParentNode("blockquote", text_to_children(quote_text))


def parse_list_block(block):
    items = []
    for line in block.split("\n"):
        if not line.strip():
            continue
        indent = len(re.match(r'^( *)', line).group(1))
        stripped = line[indent:]
        ordered_match = re.match(r'^(\d+)\.\s+(.*)$', stripped)
        if ordered_match:
            text = ordered_match.group(2).strip()
            ordered = True
        else:
            unordered_match = re.match(r'^[-+*]\s+(.*)$', stripped)
            if unordered_match:
                text = unordered_match.group(1).strip()
                ordered = False
            else:
                continue
        items.append({
            "indent": indent,
            "text": text,
            "ordered": ordered,
            "children": [],
        })
    return items


def build_nested_list_tree(items):
    root = {"indent": -1, "ordered": False, "children": []}
    stack = [root]
    for item in items:
        while stack and item["indent"] <= stack[-1]["indent"]:
            stack.pop()
        stack[-1]["children"].append(item)
        stack.append(item)
    return root["children"]


def build_list_node(block, ordered):
    items = parse_list_block(block)
    nested_items = build_nested_list_tree(items)

    def build_list(nodes, ordered_type):
        children = []
        for node in nodes:
            li_children = text_to_children(node["text"])
            if node["children"]:
                nested = build_list(node["children"], node["ordered"])
                li_children.append(nested)
            children.append(ParentNode("li", li_children))
        tag = "ol" if ordered_type else "ul"
        return ParentNode(tag, children)

    return build_list(nested_items, ordered)


def build_unordered_list_node(block):
    return build_list_node(block, ordered=False)


def build_ordered_list_node(block):
    return build_list_node(block, ordered=True)


def build_code_node(block):
    code_text = block[3:-3].strip() if block.startswith("```") and block.endswith("```") else block.strip()
    return ParentNode("pre", [text_node_to_html_node(TextNode(code_text, TextType.CODE))])


def build_block_node(block):
    block_type = block_to_block_type(block)
    if block_type == BlockType.HEADING:
        return build_heading_node(block)
    if block_type == BlockType.PARAGRAPH:
        return build_paragraph_node(block)
    if block_type == BlockType.QUOTE:
        return build_quote_node(block)
    if block_type == BlockType.UNORDERED_LIST:
        return build_unordered_list_node(block)
    if block_type == BlockType.ORDERED_LIST:
        return build_ordered_list_node(block)
    if block_type == BlockType.CODE:
        return build_code_node(block)
    raise ValueError(f"Unsupported block type: {block_type}")


def markdown_to_html_node(markdown):
    blocks = markdown_to_blocks(markdown)
    block_nodes = [build_block_node(block) for block in blocks]
    return ParentNode("div", block_nodes)


def clear_directory(path):
    if not path.exists():
        return
    for child in path.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def copy_directory_recursive(src, dst):
    if not src.exists():
        raise FileNotFoundError(f"Source directory does not exist: {src}")

    if dst.exists():
        clear_directory(dst)
    else:
        dst.mkdir(parents=True, exist_ok=True)

    for item in src.iterdir():
        dst_item = dst / item.name
        if item.is_dir():
            dst_item.mkdir(parents=True, exist_ok=True)
            copy_directory_recursive(item, dst_item)
        else:
            shutil.copy2(item, dst_item)
            print(f"Copied file: {dst_item}")


def main():
    basepath = sys.argv[1] if len(sys.argv) > 1 else "/"
    source = Path(__file__).resolve().parents[1] / "static"
    destination = Path(__file__).resolve().parents[1] / "docs"

    print(f"Cleaning destination directory: {destination}")
    clear_directory(destination)
    print(f"Copying contents from {source} to {destination}")
    copy_directory_recursive(source, destination)

    content_source = Path(__file__).resolve().parents[1] / "content"
    template_source = Path(__file__).resolve().parents[1] / "template.html"

    generate_pages_recursive(content_source, template_source, destination, basepath=basepath)

    node = TextNode("This is some anchor text", TextType.LINK, "https://www.boot.dev")
    print(node)

if __name__ == "__main__":
    main()
